### ISSUE TITLE
Proposal about trans-logo

### ISSUE THREAD

**Issue by ke1ewang** [liu-qilong/college-beamer#8]
I noticed that the location of the color-logo and the trans-logo is actually the same, but the trans-logo does not have a rectangular package, and its position looks a little strange(not aligned with the right element). Would it be better to change the trans-logo to a white background logo or adjust the position of the trans-logo?
![CleanShot 2024-09-25 at 14 38 07](https://github.com/user-attachments/assets/1680178e-4037-41dd-afcd-4e6b92cd7643)
![CleanShot 2024-09-25 at 14 40 32](https://github.com/user-attachments/assets/323b5b14-6c44-411d-8fc4-2d7282cc374c)

**Comment by liu-qilong** [comment]
Thank you for your contribution and suggestions! I think this is a good idea. I have merged your pull request.

**Comment by liu-qilong** [comment]
I've mentioned your suggestion of using white color background logo in README

**Comment by ke1ewang** [comment]
> Thank you for your contribution and suggestions! I think this is a good idea. I have merged your pull request.

This cover screenshot I made myself is different from the ones above, maybe you can adjust it to the same style. Thank you.😊
![CleanShot 2024-09-27 at 13 44 45](https://github.com/user-attachments/assets/570bec91-e4e8-4966-9121-9f061f5bfd34)

**Comment by liu-qilong** [comment]
> This cover screenshot I made myself is different from the ones above, maybe you can adjust it to the same style. Thank you.😊

Done👌 I have replace the image.

It seems that you are a macOS user too. For your reference, if you use the in-built Screenshot app, you can opt to [Capture Selected Window](https://support.apple.com/guide/mac-help/take-a-screenshot-mh26782/mac), which yields the image like mine. This feature is supper convenient.

**Comment by ke1ewang** [comment]
> > This cover screenshot I made myself is different from the ones above, maybe you can adjust it to the same style. Thank you.😊
> 
> Done👌 I have replace the image.
> 
> It seems that you are a macOS user too. For your reference, if you use the in-built Screenshot app, you can opt to [Capture Selected Window](https://support.apple.com/guide/mac-help/take-a-screenshot-mh26782/mac), which yields the image like mine. This feature is supper convenient.

Okay, thank you for your tips.
